version: '3.8'

services:
  # 1. Banco de Dados (PostgreSQL)
  db:
    image: postgres:15
    container_name: pi2-database
    restart: always
    environment:
      POSTGRES_DB: projeto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    networks:
      - pi2-network

  # 2. Backend (Java Spring)
  backend:
    build: ./backend
    container_name: pi2-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/projeto_db
      DB_USERNAME: postgres
      DB_PASSWORD: 123
      DB_DRIVER: org.postgresql.Driver
      DB_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    networks:
      - pi2-network

  # 3. Frontend (HTML/JS)
  frontend:
    build: ./frontend
    container_name: pi2-frontend
    restart: always
    ports:
      - "3000:80"  # Acesse no navegador via http://localhost:3000
    networks:
      - pi2-network
      
  # 4. Simulador de Impressoras (Java)
  simulator:
    build: ./simulator       
    container_name: pi2-simulator
    restart: always
    depends_on:
      - backend              # Só liga depois que o Backend estiver de pé
    networks:
      - pi2-network        


networks:
  pi2-network:               
    driver: bridge