services:
  # 1. Banco de Dados (PostgreSQL)
  db:
    image: postgres:15
    container_name: pi2-database
    environment:
      POSTGRES_DB: projeto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    networks:
      - pi2-network

  # 2. Backend (Java Spring)
  backend:
    build: ./backend
    container_name: pi2-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/projeto_db
      DB_USERNAME: postgres
      DB_PASSWORD: 123
      DB_DRIVER: org.postgresql.Driver
      DB_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    networks:
      - pi2-network

  # 3. Frontend (HTML/JS)
  frontend:
    build: ./frontend
    container_name: pi2-frontend
    ports:
      - "3000:80"  # Acesse no navegador via http://localhost:3000
    networks:
      - pi2-network

networks:
  pi2-network:
    driver: bridge